export type Status='Vaccinated'|'Due Soon'|'Overdue'|'Unvaccinated';
export type Dog={id:string;tagId:string;nickname:string;photo:string;gender:string;ageEstimate:string;colour:string;features:string;latitude:number;longitude:number;area:string;ward:string;vaccinationStatus:Status;vaccinationHistory:{date:string;vaccine:string;by:string}[];nextDue:string;sterilisationStatus:boolean;healthStatus:string;lastSeen:string;organisation:string;priorityScore:number;verified:boolean;movement:{area:string;date:string;lat:number;lng:number}[];treatments:{date:string;note:string}[];assigned?:string;completed?:boolean};
export const areas=[{name:'JP Nagar',code:'JPN',lat:12.9063,lng:77.5857},{name:'Jayanagar',code:'JYN',lat:12.925,lng:77.5938},{name:'Banashankari',code:'BSK',lat:12.9255,lng:77.5468},{name:'BTM Layout',code:'BTM',lat:12.9166,lng:77.6101},{name:'Koramangala',code:'KOR',lat:12.9352,lng:77.6245},{name:'HSR Layout',code:'HSR',lat:12.9116,lng:77.6389},{name:'Indiranagar',code:'IND',lat:12.9784,lng:77.6408},{name:'Whitefield',code:'WFD',lat:12.9698,lng:77.75},{name:'Malleshwaram',code:'MAL',lat:13.0031,lng:77.5643},{name:'Yelahanka',code:'YEL',lat:13.1007,lng:77.5963},{name:'Hebbal',code:'HEB',lat:13.0354,lng:77.5988}];
export const roles=['BBMP / Municipal Admin','NGO Worker','Veterinarian','Field Volunteer','Verified Community Feeder'];
export const today=()=>new Date().toISOString().slice(0,10);
export const dateOffset=(n:number)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
export const photos=['/dog-1.jpg','/dog-2.jpg','/dog-3.jpg'];
export function seed():Dog[]{return ['Bruno','Milo','Luna','Chutki','Biscuit','Raja','Chikki','Buddy','Tara','Simba','Moti','Pepper','Coco','Ginger','Kalu','Champa','Lucky','Rani','Oreo','Bholu','Sunny','Bella','Rocky','Pihu','Sheru','Zoya','Tiger','Maya','Bambi','Nandi','Cookie','Appu','Ruby'].map((name,i)=>{let a=areas[i%11],status:Status=i%7===2?'Unvaccinated':i%7===3?'Overdue':i%7===1?'Due Soon':'Vaccinated';let lat=a.lat+(i%3-1)*.006,lng=a.lng+(i%4-2)*.004;return {id:`PAW-BLR-${a.code}-${String(i===0?124:i===1?225:i===2?326:400+i).padStart(6,'0')}`,tagId:`PC-${1000+i}`,nickname:name,photo:photos[i%3],gender:i%2?'Female':'Male',ageEstimate:`${2+i%6} years`,colour:['Golden tan','White & brown','Black & white'][i%3],features:['Folded ears, white chest patch','Upright ears, curled tail','Notched left ear, spotted paws'][i%3],latitude:lat,longitude:lng,area:a.name,ward:`${a.name} ward`,vaccinationStatus:status,vaccinationHistory:status==='Unvaccinated'?[]:[{date:dateOffset(status==='Overdue'?-399:status==='Due Soon'?-350:-100),vaccine:'Anti-rabies vaccine',by:'Dr. Asha · Care Collective'}],nextDue:status==='Unvaccinated'?'':dateOffset(status==='Overdue'?-34:status==='Due Soon'?15:265),sterilisationStatus:i%4!==2,healthStatus:i%9===2?'Needs medical attention':'Healthy',lastSeen:dateOffset(-(i%8)),organisation:['Care Collective','Bengaluru Paws','BBMP Animal Husbandry'][i%3],priorityScore:0,verified:i%6!==0,movement:[{area:a.name,date:dateOffset(-60),lat:a.lat,lng:a.lng},{area:areas[(i+1)%11].name,date:dateOffset(-15),lat:areas[(i+1)%11].lat,lng:areas[(i+1)%11].lng},{area:a.name,date:dateOffset(-(i%8)),lat,lng}],treatments:[{date:dateOffset(-50),note:'Routine health check and deworming'}]}})}
export function statusOf(d:Dog):Status{if(!d.vaccinationHistory.length)return 'Unvaccinated';let days=(new Date(d.nextDue).getTime()-new Date(today()).getTime())/86400000;return days<0?'Overdue':days<=30?'Due Soon':'Vaccinated'}
export function priority(d:Dog,all:Dog[]){let group=all.filter(x=>x.area===d.area),coverage=group.filter(x=>['Vaccinated','Due Soon'].includes(statusOf(x))).length/group.length;let reasons:{label:string;value:number}[]=[];if(statusOf(d)==='Overdue')reasons.push({label:'Vaccination overdue',value:40});if(statusOf(d)==='Unvaccinated')reasons.push({label:'Unvaccinated',value:25});if(coverage<.7)reasons.push({label:'Area coverage below 70%',value:15});if(Date.now()-new Date(d.lastSeen).getTime()<7*86400000)reasons.push({label:'Recently sighted',value:10});if(d.healthStatus!=='Healthy')reasons.push({label:'Medical risk',value:10});return {score:reasons.reduce((s,r)=>s+r.value,0),reasons}}
export const loadDogs=():Dog[]=>{try{const value=JSON.parse(localStorage.getItem('pawcare-dogs')||'null');if(Array.isArray(value)&&value.length)return value;}catch{}return seed()};


